# Generated by Django 3.0.2 on 2020-02-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='idEstado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idPedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
